### PR TITLE
Update GSW to 2023 FAR DPF Launch version.

### LINKED ISSUE #37: Update working-set of version-controlled GSW.
Currently, due to the lack of nice deployment infrastructure (set to be fixed by #36), we've simply been making a bunch of local changes to the GSW (RPi Ground Systems software on the RPi), and not actually checking these changes into this repo. Let's do that check in here, and in the process also re-evaluate (add/remove) tracked files as necessary (i.e. `cctv.service`, `grafana-server.service`, `/etc/dhcpcd.conf`, etc. needs to be tracked).

Blocked by #36.
Blocks #16.

### PR DESCRIPTION
**Pull request by harrisonCassar**
Addresses #37.

Updates entirety of GSW to latest version (the version of GSW deployed on the RPi, or the version of GSW used in the 2023 FAR DPF Launch), including updating existing-tracked files, as well as adding tracking for a number of other files that were being used/modified but not yet tracked (including some Grafana config files, Telegraf config files, and a few `*.service` files).

Will unblock #16, which desires to setup deployment for all of these files.

### CODE REVIEW

**Comment by harrisonCassar** [comment]
NOTE: Based on some downstream work getting started while waiting for reviews, let's wrap up PR#45 before merging this PR.

**Review by philipdoucla — DISMISSED** [review]
Looks good, wanna take a look at the merge conflict?

**Comment by harrisonCassar** [comment]
Rebased on main and fixed the merge conflict! Ready for review again! @philipdoucla

**Review by philipdoucla — APPROVED** [review]
Seems to be a lot of comments here but the code looks good!

**Pull request merged**
